<a href="https://colab.research.google.com/github/ShivanshGanguly/DAV-Lab/blob/main/DAV_Lab_01_NumPy_Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Data Analytics and Visualisation")

Welcome to Data Analytics and Visualisation


In [ ]:
import pandas as pd
import numpy as np

print("Numpy version: ",np.__version__)
print("Pandas version: ",pd.__version__)

Numpy version:  2.0.2
Pandas version:  2.2.3


In [ ]:
marks = np.array([78,85,92,67,88])
print("Marks: ",marks)
print("Type: ",type(marks))

Marks:  [78 85 92 67 88]
Type:  <class 'numpy.ndarray'>


In [ ]:
print("Number of dimensions: ",marks.ndim)
print("Shape: ",marks.shape)
print("Number of elements: ",marks.size)

Number of dimensions:  1
Shape:  (5,)
Number of elements:  5


In [ ]:
print("Original: ",marks)
print("Add 5: ",marks+5)
print("Multiply by 2: ",marks*2)
print("Divide by 2: ",marks/2)
print("Square: ",marks**2)

Original:  [78 85 92 67 88]
Add 5:  [83 90 97 72 93]
Multiply by 2:  [156 170 184 134 176]
Divide by 2:  [39.  42.5 46.  33.5 44. ]
Square:  [6084 7225 8464 4489 7744]


In [ ]:
print("Sum: ",marks.sum())
print("Mean: ",marks.mean())
print("Maximum: ",marks.max())
print("Minimum: ",marks.min())

Sum:  410
Mean:  82.0
Maximum:  92
Minimum:  67


In [ ]:
print("First marks: ",marks[0])
print("Second marks: ",marks[1])
print("Last marks: ",marks[-1])

First marks:  78
Second marks:  85
Last marks:  88


In [ ]:
print("Index 1 to 3: ",marks[1:4])
print("First three: ",marks[:3])
print("From index 2: ",marks[2:])
print("Every second element: ",marks[::2])

Index 1 to 3:  [85 92 67]
First three:  [78 85 92]
From index 2:  [92 67 88]
Every second element:  [78 92 88]


In [ ]:
student_marks = np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
    ])
print(student_marks)
print(student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
(3, 3)


In [ ]:
print("Mean of all values: ",student_marks.mean())
print("Column wise mean: ",student_marks.mean(axis=0))
print("Row wise mean: ",student_marks.mean(axis=1))

Mean of all values:  84.44444444444444
Column wise mean:  [78.33333333 89.33333333 85.66666667]
Row wise mean:  [85.         77.         91.33333333]


**PANDAS**

In [ ]:
data = {
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Branch": ["CSE","AIML","CSE","AIML"],
    "Marks": [85,91,76,88]
}
df = pd.DataFrame(data)
df

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
print("Shape",df.shape)
print("\nColumns")
print(df.columns)

Shape (4, 3)

Columns
Index(['Name', 'Branch', 'Marks'], dtype='object')


In [ ]:
df.head()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.tail()

,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
df.describe()

,Marks
count,4.000000
mean,85.000000
std,6.480741
min,76.000000
25%,82.750000
50%,86.500000
75%,88.750000
max,91.000000


In [ ]:
print("Marks column:")
print(df["Marks"])
print("\nBranch and Marks column:")
print(df[["Branch","Marks"]])

Marks column:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

Branch and Marks column:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88


In [ ]:
print("First row:")
print(df.iloc[0])#iloc is for integer location based indexing
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[0:3])
print("\nFirst two rows and first 2 columns:")
print(df.iloc[0:2,0:2])

First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

First two rows and first 2 columns:
    Name Branch
0    Anu    CSE
1  Rahul   AIML


In [ ]:
print("First three rows:")
display(df.iloc[0:3])
print("\nRows 1 to 3 Name and Marks:")
display(df.iloc[1:4,0:3])

First three rows:


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
2,Kiran,CSE,76



Rows 1 to 3 Name and Marks:


,Name,Branch,Marks
1,Rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
high_scorers = df[df["Marks"]>90]
high_scorers

,Name,Branch,Marks
1,Rahul,AIML,91


In [ ]:
print("Students from CSE:")
display(df[df["Branch"] == "CSE"])

print("\nStudents scoring 85 or above:")
display(df[df["Marks"] >= 85])

Students from CSE:


,Name,Branch,Marks
0,Anu,CSE,85
2,Kiran,CSE,76



Students scoring 85 or above:


,Name,Branch,Marks
0,Anu,CSE,85
1,Rahul,AIML,91
3,Priya,AIML,88


In [ ]:
stud_data = {
    "Name": ["Anu","Rahul","Kiran","Priya","Shweta"],
    "Department": ["CSE","AIML","CSE","AIML","CSE"],
    "Marks": [85,91,76,88,92],
    "Attendance": [91,90,22,12,90]
}
df = pd.DataFrame(stud_data)
df

,Name,Department,Marks,Attendance
0,Anu,CSE,85,91
1,Rahul,AIML,91,90
2,Kiran,CSE,76,22
3,Priya,AIML,88,12
4,Shweta,CSE,92,90


In [ ]:
display(df[["Name","Marks"]])
print("\nStudents scoring 80 or above:")
display(df[df["Marks"] >= 80])
print("\nStudents attending 85% or above:")
display(df[df["Attendance"] >= 85])
print("\nFirst three students:")
display(df.iloc[0:3])
print("\nAverage Marks: ",df["Marks"].mean())
print("\nMaximum Marks: ",df["Marks"].max())
print("\nStudents from CSE:")
display(df[df["Department"] == "CSE"])
print("\n")
display(df[(df["Marks"] > 80) & (df["Attendance"]> 85)])

,Name,Marks
0,Anu,85
1,Rahul,91
2,Kiran,76
3,Priya,88
4,Shweta,92



Students scoring 80 or above:


,Name,Department,Marks,Attendance
0,Anu,CSE,85,91
1,Rahul,AIML,91,90
3,Priya,AIML,88,12
4,Shweta,CSE,92,90



Students attending 85% or above:


,Name,Department,Marks,Attendance
0,Anu,CSE,85,91
1,Rahul,AIML,91,90
4,Shweta,CSE,92,90



First three students:


,Name,Department,Marks,Attendance
0,Anu,CSE,85,91
1,Rahul,AIML,91,90
2,Kiran,CSE,76,22



Average Marks:  86.4

Maximum Marks:  92

Students from CSE:


,Name,Department,Marks,Attendance
0,Anu,CSE,85,91
2,Kiran,CSE,76,22
4,Shweta,CSE,92,90


,Name,Department,Marks,Attendance
0,Anu,CSE,85,91
1,Rahul,AIML,91,90
4,Shweta,CSE,92,90
